apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "myapp"
  annotations:
    "humanitec.com/orgId": "humanitec-acn"
    "humanitec.com/appId": "myapp"
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
